name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1


    - name: Build the Docker image
      env: 
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        deploy_key: ${{ secrets.DOCKER_CERT_PATH }}
        DOCKER_HOST: ssh://vlada92ceo@35.246.151.122
      run: |
        mkdir -p ~/.ssh
        #ssh-keyscan 35.246.151.122 > ~/.ssh/known_hosts      
        #ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        #ssh-add - <<< " $"
        echo "${deploy_key}" >> ~/.ssh/id_rsa
        sudo chmod 400 ~/.ssh/id_rsa
        ls -la ~/.ssh/id_rsa
        docker-compose -f docker-compose.yml up -d frontend
      
        
        
      
