name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v1
    - name: Configuration
      env:
       deploy_key: ${{ secrets.deploy_key }}
      run: |
       touch ~/gcp
       echo $deploy_key > ~/gcp
       sudo chmod 400 ~/gcp
       ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  vlada92ceo@35.246.151.122 -i gcp
       
    - name: install latest compose
      run: |
       sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
       sudo chmod +x /usr/local/bin/docker-compose
       sudo add-apt-repository ppa:deadsnakes/ppa -y
       sudo apt install python3.7 -y
    - name: check version of docker-compose
      run: docker-compose -v        
    - name: Build the Docker image
      run: docker-compose -H  ssh://vlada92ceo@35.246.151.122 -f docker-compose.yml up -d frontend 

