name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
     env:
      deploy_key: ${{ secrets.deploy_key }}
    steps:
    - uses: actions/checkout@v1
    - name: Configuration
      run: |
       echo $deploy_key
      # eval "$(ssh-agent -s)"
      # ssh-add - <<< ${deploy_key}         
    - name: Build the Docker image
      run: docker-compose -H  ssh://vlada92ceo@35.246.151.122:2375 -f docker-compose.yml up -d frontend 

