name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1


    - name: Build the Docker image
      env: 
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        deploy_key: ${{ secrets.DOCKER_CERT_PATH }}
      run: |
        sudo curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        mkdir -p ~/.ssh
        #ssh-keyscan 35.246.151.122 > ~/.ssh/known_hosts      
        #ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        #ssh-add - <<< " $"
        echo "${deploy_key}" >> ~/.ssh/id_rsa
        sudo chmod 400 ~/.ssh/id_rsa
        docker-compose -H  ssh://vlada92ceo@35.246.151.122:2375 -f docker-compose.yml up -d frontend
      
        
        
      
