name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v1
    - name: Configuration
      env:
       deploy_key: ${{ secrets.deploy_key }}
      run: |
       pwd
       ls -la ~/.ssh       
    - name: Build the Docker image
      env:
       deploy_key: ${{ secrets.deploy_key }}
       DOCKER_HOST: ssh://vlada92ceo@35.246.151.122
      run: |
       #touch gcp
       #echo "${deploy_key}" >> gcp
       #sudo chmod 400 gcp
       #ssh -i gcp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  vlada92ceo@35.246.151.122
       docker -H ssh://vlada92ceo@35.246.151.122 images
      #run: docker-compose -f docker-compose.yml up -d frontend 

