name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v1
    - name: Configuration
      env:
       DOCKER_HOST: ssh://vlada92ceo@35.246.151.122
       deploy_key: ${{ secrets.deploy_key }}
      run: |
       touch gcp
       echo "${deploy_key}" >> gcp
       sudo chmod 400 gcp
       ssh -i gcp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  vlada92ceo@35.246.151.122 
       
    - name: check version of docker-compose
      run: docker-compose -v        
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yml up -d frontend 

