name: Docker Image CI

on: [push]

jobs:

build:

runs-on: ubuntu-latest
container:
        # image: mysql:8.0 
        #env:
        # MYSQL_ROOT_PASSWORD: .sweetpwd.
        # MYSQL_DATABASE: my_db
        # MYSQL_USER: db_user
        # MYSQL_PASSWORD: .mypwd
        # ports:
        # - 8082:3306
        #volumes:
container: 
image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=.sweetpwd.
          - MYSQL_DATABASE=my_db
          - MYSQL_USER=db_user
          - MYSQL_PASSWORD=.mypwd
        ports:
          - "8082:3306"              
